using System;
using System.IO;
using System.Text;
using System.Linq;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Windows.Forms;
using OneCConfigExporter;
class VerifyLocalFirstSync {
 static string git,root;static Type sync,main;static BindingFlags flags=BindingFlags.Instance|BindingFlags.NonPublic;
 static void Check(bool value,string message){if(!value)throw new Exception(message);}
 static string Quote(string value){return "\""+value.Replace("\"","\\\"")+"\"";}
 static async Task<Tuple<int,string>> Native(string folder,string command){using(var p=Process.Start(new ProcessStartInfo{FileName=git,Arguments="-c core.longpaths=true -c core.quotepath=false -C "+Quote(folder)+" "+command,UseShellExecute=false,CreateNoWindow=true,RedirectStandardOutput=true,RedirectStandardError=true,StandardOutputEncoding=Encoding.UTF8,StandardErrorEncoding=Encoding.UTF8})){
  var stdout=p.StandardOutput.ReadToEndAsync();var stderr=p.StandardError.ReadToEndAsync();if(!p.WaitForExit(30000)){p.Kill();throw new Exception("Native Git timeout: "+command);}await Task.WhenAll(stdout,stderr);return Tuple.Create(p.ExitCode,(stdout.Result+stderr.Result).Trim());
 }}
 static string G(string folder,string command){var r=Native(folder,command).GetAwaiter().GetResult();Check(r.Item1==0,"Fixture Git: "+command+"\n"+r.Item2);return r.Item2;}
 static void Config(string folder){G(folder,"config core.longpaths true");G(folder,"config user.name Test");G(folder,"config user.email test@example.invalid");}
 static void Commit(string folder,string text,string message){File.WriteAllText(Path.Combine(folder,"Configuration.xml"),text);G(folder,"add -A");G(folder,"commit -m "+Quote(message));}
 class Fixture {
  public string Local,Writer,Remote,LocalHead,RemoteHead,Tree;public int Pushes,Fetches,Merges;public bool Cancel;public Func<string,Task<Tuple<int,string>>> Override;
  public List<string> Commands=new List<string>(),Done=new List<string>(),Events=new List<string>();
  public Fixture(string name,string mode){string dir=Path.Combine(root,name);Directory.CreateDirectory(dir);Local=Path.Combine(dir,"local's $() &; файлы");Writer=Path.Combine(dir,"writer");Remote=Path.Combine(dir,"remote.git");Directory.CreateDirectory(Local);Directory.CreateDirectory(Writer);Directory.CreateDirectory(Remote);G(Remote,"init --bare --initial-branch=main");G(Remote,"config core.longpaths true");G(Writer,"init --initial-branch=main");Config(Writer);
   if(mode!="empty"){Commit(Writer,"<remote>root</remote>","remote root");G(Writer,"push "+Quote(Remote)+" HEAD:refs/heads/main");}
   if(mode=="diverged"||mode=="behind"||mode=="same"){G(dir,"clone "+Quote(Remote)+" "+Quote(Local));Config(Local);if(mode=="diverged")Commit(Local,"<local>current export</local>","local export");if(mode!="same"){File.WriteAllText(Path.Combine(Writer,"remote-only.txt"),"server only");Commit(Writer,"<remote>new</remote>","remote newer");G(Writer,"push "+Quote(Remote)+" HEAD:refs/heads/main");}}
   else{G(Local,"init --initial-branch=main");Config(Local);Commit(Local,"<local>full export</local>","local full");Commit(Local,"<local>incremental export</local>","local incremental");}
   LocalHead=G(Local,"rev-parse HEAD");Tree=G(Local,"rev-parse HEAD^{tree}");RemoteHead=mode=="empty"?null:G(Remote,"rev-parse refs/heads/main");
   // These untracked service files must survive reconciliation byte-for-byte.
   File.WriteAllText(Path.Combine(Local,"1c-dump.log"),"dump log");File.WriteAllText(Path.Combine(Local,".onecexporter.lock"),"lock");
  }
  public async Task<Tuple<int,string>> Run(string command,bool auth){Commands.Add(command);bool network=command.StartsWith("push ")||command.StartsWith("fetch ");Check(auth==network,"Only push/fetch receive GitHub auth");Check(!command.Contains("--force")&&!command.StartsWith("reset ")&&!command.StartsWith("clean ")&&!command.Contains("+refs/"),"No destructive history/file operation");if(command.StartsWith("push "))Pushes++;if(command.StartsWith("fetch "))Fetches++;if(command.StartsWith("merge "))Merges++;
   if(Override!=null){var injected=await Override(command);if(injected!=null)return injected;}
   return await Native(Local,command.Replace(Quote("https://github.com/test/sync.git"),Quote(Remote)));
  }
  public Task<string> Start(){return (Task<string>)sync.GetMethod("PushAsync").Invoke(null,new object[]{new Func<string,bool,Task<Tuple<int,string>>>(Run),"https://github.com/test/sync.git","main",new Func<bool>(()=>Cancel),new Action<string>(Events.Add),new Action<string>(Events.Add),new Action<string>(Done.Add),new Func<string,string>(s=>"Push failure: "+s)});}
  public string Execute(){return Start().GetAwaiter().GetResult();}
  public void VerifySuccess(bool merged){Check(G(Local,"rev-parse HEAD^{tree}")==Tree,"Entire local tree retained");Check(G(Remote,"rev-parse refs/heads/main")==G(Local,"rev-parse HEAD"),"Verified commit sent to expected remote branch");Check(File.ReadAllText(Path.Combine(Local,"1c-dump.log"))=="dump log"&&File.ReadAllText(Path.Combine(Local,".onecexporter.lock"))=="lock","Service files retained");G(Local,"merge-base --is-ancestor "+LocalHead+" HEAD");if(RemoteHead!=null)G(Local,"merge-base --is-ancestor "+RemoteHead+" HEAD");Check(G(Local,"for-each-ref --format=%(refname) refs/onecexporter-fetch")=="","Private fetch ref cleaned");string backups=G(Local,"for-each-ref --format=%(objectname) refs/heads/onecexporter-backup/");Check(merged?backups.Contains(LocalHead)&&backups.Contains(RemoteHead):backups=="","Both backup tips retained only when needed");Check(Done.Any(x=>x.Contains("отправлены на GitHub")),"Success included in completed steps");Check(merged==Done.Any(x=>x.Contains("Истории Git согласованы")),"Reconciliation summary matches actual work");}
 }
 static string Reject(Fixture f,string type="[rejected] (non-fast-forward)"){return "!\t"+f.LocalHead+":refs/heads/main\t"+type;}
 static void Wait(Task task){var end=DateTime.UtcNow.AddSeconds(90);while(!task.IsCompleted&&DateTime.UtcNow<end){Application.DoEvents();Thread.Sleep(10);}Check(task.IsCompleted,"UI timeout");task.GetAwaiter().GetResult();}
 static IEnumerable<Control> Descendants(Control parent){foreach(Control child in parent.Controls){yield return child;foreach(Control nested in Descendants(child))yield return nested;}}
 [STAThread]static void Main(string[] args){
  git=args[2];root=Path.Combine(args[0],"sync-"+Guid.NewGuid().ToString("N").Substring(0,8));Directory.CreateDirectory(root);var assembly=typeof(UserSettings).Assembly;sync=assembly.GetType("OneCConfigExporter.GitLocalFirstSync");main=assembly.GetType("OneCConfigExporter.MainForm");
  var normal=new Fixture("normal","empty");G(normal.Local,"tag -a test-tag -m test");G(normal.Local,"config push.followTags true");Check(normal.Execute()==null&&normal.Pushes==1&&normal.Fetches==0,"Ordinary push has no reconciliation");normal.VerifySuccess(false);Check((awaitless(normal.Remote,"show-ref --tags")).Item1==1,"Unrequested tags not sent");
  foreach(string mode in new[]{"unrelated","diverged","behind"}){var f=new Fixture(mode,mode);File.WriteAllText(Path.Combine(f.Local,".git","FETCH_HEAD"),"external-fetch-marker");Check(f.Execute()==null,"Automatic reconciliation: "+mode);Check(f.Pushes==2&&f.Fetches==1&&f.Merges==1,"Exactly one retry: "+mode);f.VerifySuccess(true);Check(File.ReadAllText(Path.Combine(f.Local,".git","FETCH_HEAD"))=="external-fetch-marker","FETCH_HEAD not overwritten/used");if(mode!="unrelated")Check(!File.Exists(Path.Combine(f.Local,"remote-only.txt")),"Remote-only file not imported");}
  var same=new Fixture("already-included","same");same.Override=c=>Task.FromResult(c.StartsWith("push ")&&same.Pushes==1?Tuple.Create(1,Reject(same)):null);Check(same.Execute()==null&&same.Merges==0&&same.Pushes==2,"Already included remote history does not create a fake merge");same.VerifySuccess(false);
  foreach(string blocked in new[]{"staged","dirty","merge","rebase"}){var f=new Fixture("blocked-"+blocked,"unrelated");if(blocked=="staged"){File.WriteAllText(Path.Combine(f.Local,"outside.txt"),"foreign staged");G(f.Local,"add outside.txt");}if(blocked=="dirty")File.WriteAllText(Path.Combine(f.Local,"Configuration.xml"),"foreign working");if(blocked=="merge")File.WriteAllText(Path.Combine(f.Local,".git","MERGE_HEAD"),f.LocalHead);if(blocked=="rebase")Directory.CreateDirectory(Path.Combine(f.Local,".git","rebase-merge"));string before=G(f.Local,"diff --cached --binary");Check(f.Execute()!=null&&f.Pushes==1&&f.Fetches==0&&f.Merges==0,"Unsafe state blocked: "+blocked);Check(G(f.Local,"rev-parse HEAD")==f.LocalHead&&G(f.Local,"diff --cached --binary")==before,"No index or commit change: "+blocked);}
  foreach(string error in new[]{"fatal: HTTP 403", "remote: error: GH001 large file", "[remote rejected] (protected branch hook declined)"}){var f=new Fixture("reject-"+Guid.NewGuid().ToString("N").Substring(0,8),"unrelated");f.Override=c=>Task.FromResult(c.StartsWith("push ")?Tuple.Create(1,Reject(f,error)):null);Check(f.Execute()!=null&&f.Pushes==1&&f.Fetches==0&&f.Merges==0,"Not a history rejection: "+error);}
  var race=new Fixture("remote-race","unrelated");race.Override=c=>{if(c.StartsWith("push ")&&race.Pushes==2){Commit(race.Writer,"<remote>parallel update</remote>","parallel update");G(race.Writer,"push "+Quote(race.Remote)+" HEAD:refs/heads/main");}return Task.FromResult<Tuple<int,string>>(null);};string failed=race.Execute();Check(failed!=null&&failed.Contains("Новых автоматических попыток")&&race.Pushes==2&&race.Merges==1&&G(race.Local,"rev-parse HEAD^{tree}")==race.Tree,"Repeated rejection is bounded and retains local tree");
  var backupFail=new Fixture("backup-fail","unrelated");backupFail.Override=c=>Task.FromResult(c.StartsWith("branch ")&&c.Contains("/github")?Tuple.Create(1,"backup refused"):null);Check(backupFail.Execute()!=null&&backupFail.Pushes==1&&backupFail.Merges==0&&G(backupFail.Local,"rev-parse HEAD")==backupFail.LocalHead,"Backup failure stops before merge");
  var cancellation=new Fixture("cancel","unrelated");cancellation.Override=async c=>{if(c.StartsWith("fetch ")){var result=await Native(cancellation.Local,c.Replace(Quote("https://github.com/test/sync.git"),Quote(cancellation.Remote)));cancellation.Cancel=true;return result;}return null;};Check(cancellation.Execute()!=null&&cancellation.Pushes==1&&cancellation.Merges==0&&G(cancellation.Local,"rev-parse HEAD")==cancellation.LocalHead,"Cancellation stops before mutation");
  var tamper=new Fixture("tampered-tree","unrelated");tamper.Override=async c=>{if(c.StartsWith("merge ")){var result=await Native(tamper.Local,c);Commit(tamper.Local,"<foreign>hook update</foreign>","hook changed tree");return result;}return null;};Check(tamper.Execute()!=null&&tamper.Pushes==1&&G(tamper.Remote,"rev-parse refs/heads/main")==tamper.RemoteHead,"Unexpected tree mutation is not uploaded");
  var replacedFetch=new Fixture("external-fetch","unrelated");replacedFetch.Override=async c=>{if(c.StartsWith("fetch ")){var result=await Native(replacedFetch.Local,c.Replace(Quote("https://github.com/test/sync.git"),Quote(replacedFetch.Remote)));File.WriteAllText(Path.Combine(replacedFetch.Local,".git","FETCH_HEAD"),replacedFetch.LocalHead+"\n");return result;}return null;};Check(replacedFetch.Execute()==null,"Concurrent FETCH_HEAD change cannot select wrong history");replacedFetch.VerifySuccess(true);
  foreach(string options in new[]{"--no-commit","--squash --no-commit"}){var f=new Fixture("opts-"+Guid.NewGuid().ToString("N").Substring(0,8),"unrelated");G(f.Local,"config branch.main.mergeOptions "+Quote(options));Check(f.Execute()==null,"Branch merge defaults overridden: "+options);f.VerifySuccess(true);}
  foreach(string flag in new[]{"--assume-unchanged","--skip-worktree"}){var f=new Fixture("flag-"+Guid.NewGuid().ToString("N").Substring(0,8),"empty");G(f.Local,"update-index "+flag+" Configuration.xml");File.WriteAllText(Path.Combine(f.Local,"Configuration.xml"),"<changed>must not be missed</changed>");string error=f.Execute();Check(error!=null&&error.Contains("skip-worktree")&&f.Pushes==0,"Hidden index cannot report stale export as sent: "+flag);}
  foreach(string special in new[]{"replace","grafts"}){var f=new Fixture(special,"unrelated");if(special=="replace")G(f.Local,"replace "+f.LocalHead+" "+G(f.Local,"rev-parse HEAD^"));else File.WriteAllText(Path.Combine(f.Local,".git","info","grafts"),f.LocalHead+"\n");Check(f.Execute()!=null&&f.Pushes==0&&f.Merges==0,"Reinterpreted history blocked: "+special);}
  var failedFetch=new Fixture("fetch-failure","unrelated");failedFetch.Override=async c=>{if(c.StartsWith("fetch ")){await Native(failedFetch.Local,c.Replace(Quote("https://github.com/test/sync.git"),Quote(failedFetch.Remote)));return Tuple.Create(1,"error after ref update");}return null;};Check(failedFetch.Execute()!=null&&failedFetch.Pushes==1&&failedFetch.Merges==0&&G(failedFetch.Local,"for-each-ref --format=%(refname) refs/onecexporter-fetch")=="","Late fetch failure cleans its exact private ref");
  var badCleanup=new Fixture("cleanup-failure","unrelated");badCleanup.Override=c=>Task.FromResult(c.StartsWith("update-ref -d ")?Tuple.Create(1,"cleanup refused"):null);Check(badCleanup.Execute()==null&&badCleanup.Pushes==2&&badCleanup.Events.Any(x=>x.Contains("Не удалось удалить временную")),"Cleanup warning does not invalidate confirmed upload");
  var ambiguous=new Fixture("ambiguous","unrelated");ambiguous.Override=c=>Task.FromResult(c.StartsWith("push ")?Tuple.Create(1,Reject(ambiguous)+"\n"+Reject(ambiguous,"[remote rejected] (protected branch)")):null);Check(ambiguous.Execute()!=null&&ambiguous.Fetches==0&&ambiguous.Merges==0,"Contradictory porcelain records do not trigger reconciliation");
  var production=new Fixture("production","unrelated");string oldGit=Environment.GetEnvironmentVariable("ONEC_SYNC_TEST_GIT"),oldRemote=Environment.GetEnvironmentVariable("ONEC_SYNC_TEST_REMOTE");Environment.SetEnvironmentVariable("ONEC_SYNC_TEST_GIT",git);Environment.SetEnvironmentVariable("ONEC_SYNC_TEST_REMOTE",production.Remote);
  try{using(var form=(Form)Activator.CreateInstance(main,true)){var handle=form.Handle;Action<string,string> set=(field,value)=>((Control)main.GetField(field,flags).GetValue(form)).Text=value;set("gitPath",Path.Combine(args[0],"FakeSyncGit.exe"));set("output",production.Local);set("githubUser","test");set("githubToken",production.LocalHead.Substring(0,8));set("dbPassword","main");set("githubRepo","test/sync");var b=new BatchBase{Name="Auto sync",Output=production.Local,Commit=true,Push=true};main.GetField("batchBases",flags).SetValue(form,new List<BatchBase>{b});main.GetMethod("ReloadBatchRows",flags).Invoke(form,null);main.GetField("activeBatchBase",flags).SetValue(form,b);var task=(Task<string>)main.GetMethod("PushToGithub",flags).Invoke(form,null);Wait(task);Check(task.Result==null,"Production GUI pipeline: "+task.Result);Check(G(production.Local,"rev-parse HEAD^{tree}")==production.Tree&&G(production.Remote,"rev-parse refs/heads/main")==G(production.Local,"rev-parse HEAD"),"Real application runner keeps exact tree");var grid=(DataGridView)main.GetField("batchGrid",flags).GetValue(form);string summary=(string)main.GetMethod("BatchDetailsText",flags).Invoke(form,new object[]{grid.Rows[0]});Check(summary.Contains("Истории Git согласованы")&&summary.Contains("отправлены на GitHub"),"Production completed-stage summary");string log=((TextBox)main.GetField("logBox",flags).GetValue(form)).Text;Check(!log.Contains(production.LocalHead.Substring(0,8)),"Machine data remains masked in UI log despite colliding token");}}
  finally{Environment.SetEnvironmentVariable("ONEC_SYNC_TEST_GIT",oldGit);Environment.SetEnvironmentVariable("ONEC_SYNC_TEST_REMOTE",oldRemote);}
  var delayedCancel=new Fixture("auth-cancel","empty");string oldDelay=Environment.GetEnvironmentVariable("ONEC_SYNC_TEST_QUERY_DELAY_MS");Environment.SetEnvironmentVariable("ONEC_SYNC_TEST_GIT",git);Environment.SetEnvironmentVariable("ONEC_SYNC_TEST_REMOTE",delayedCancel.Remote);Environment.SetEnvironmentVariable("ONEC_SYNC_TEST_QUERY_DELAY_MS","600");
  try{using(var form=(Form)Activator.CreateInstance(main,true))using(var timer=new System.Windows.Forms.Timer{Interval=100}){var handle=form.Handle;((Control)main.GetField("gitPath",flags).GetValue(form)).Text=Path.Combine(args[0],"FakeSyncGit.exe");((Control)main.GetField("output",flags).GetValue(form)).Text=delayedCancel.Local;((Control)main.GetField("githubUser",flags).GetValue(form)).Text="test";((Control)main.GetField("githubToken",flags).GetValue(form)).Text="test-only-token";timer.Tick+=(s,e)=>{main.GetField("batchStopRequested",flags).SetValue(form,true);timer.Stop();};timer.Start();var task=(Task<Tuple<int,string>>)main.GetMethod("RunGitSyncAsync",flags).Invoke(form,new object[]{"push --porcelain --no-force --no-mirror --no-follow-tags "+Quote("https://github.com/test/sync.git")+" "+Quote(delayedCancel.LocalHead+":refs/heads/main"),true});Wait(task);Check(task.Result.Item1!=0&&awaitless(delayedCancel.Remote,"rev-parse --verify refs/heads/main").Item1!=0,"Cancellation during auth checks cannot launch a late push");}}
  finally{Environment.SetEnvironmentVariable("ONEC_SYNC_TEST_GIT",oldGit);Environment.SetEnvironmentVariable("ONEC_SYNC_TEST_REMOTE",oldRemote);Environment.SetEnvironmentVariable("ONEC_SYNC_TEST_QUERY_DELAY_MS",oldDelay);}
  Environment.SetEnvironmentVariable("ONEC_SYNC_TEST_GIT",git);Environment.SetEnvironmentVariable("ONEC_SYNC_TEST_REMOTE",production.Remote);
  try{using(var form=(Form)Activator.CreateInstance(main,true)){var handle=form.Handle;Action<string,string> set=(field,value)=>((Control)main.GetField(field,flags).GetValue(form)).Text=value;set("gitPath",Path.Combine(args[0],"FakeSyncGit.exe"));set("output",production.Local);set("githubUser","test");set("githubToken","test-only-token");set("githubRepo","test/sync");G(production.Local,"config url.https://invalid.example/.pushInsteadOf https://github.com/");var task=(Task<string>)main.GetMethod("PushToGithub",flags).Invoke(form,null);Wait(task);Check(task.Result!=null&&task.Result.Contains("pushInsteadOf"),"pushInsteadOf blocked before native push");G(production.Local,"config --unset url.https://invalid.example/.pushInsteadOf");G(production.Local,"config "+Quote("remote.https://github.com/test/sync.git.url")+" https://invalid.example/");task=(Task<string>)main.GetMethod("PushToGithub",flags).Invoke(form,null);Wait(task);Check(task.Result!=null&&task.Result.Contains("полного URL"),"URL-named remote cannot redirect upload");G(production.Local,"config --unset "+Quote("remote.https://github.com/test/sync.git.url"));G(production.Local,"update-index --assume-unchanged Configuration.xml");var preflight=(Task<string>)main.GetMethod("GitPreflight",flags).Invoke(form,null);Wait(preflight);Check(preflight.Result!=null&&preflight.Result.Contains("assume-unchanged"),"GUI preflight blocks hidden export files");G(production.Local,"update-index --no-assume-unchanged Configuration.xml");}}
  finally{Environment.SetEnvironmentVariable("ONEC_SYNC_TEST_GIT",oldGit);Environment.SetEnvironmentVariable("ONEC_SYNC_TEST_REMOTE",oldRemote);}
  Check(!(bool)sync.GetMethod("HistoryRejected").Invoke(null,new object[]{Reject(production),"other",production.LocalHead}),"Rejection of another branch does not reconcile");
  string metadataFile=Path.Combine(root,"metadata.log"),metadataSecret=production.LocalHead.Substring(0,8);var logType=assembly.GetType("OneCConfigExporter.GitLog");
  string metadataInput="hook warning "+metadataSecret+"\n"+new string('x',70000)+metadataSecret+"\n"+Reject(production)+"\n";
  using(var memory=new MemoryStream(Encoding.UTF8.GetBytes(metadataInput)))using(var reader=new StreamReader(memory,Encoding.UTF8)){var task=(Task)logType.GetMethod("ReadMetadataAsync").Invoke(null,new object[]{reader,metadataFile,"stdout",new[]{metadataSecret},true});task.GetAwaiter().GetResult();var value=task.GetType().GetProperty("Result").GetValue(task,null);string raw=(string)value.GetType().GetField("Metadata").GetValue(value),shown=(string)value.GetType().GetField("Text").GetValue(value);Check(raw.Contains(production.LocalHead)&&!raw.Contains("hook warning")&&!raw.Contains(new string('x',100)),"Metadata contains only complete porcelain records");Check(!shown.Contains(metadataSecret)&&!File.ReadAllText(metadataFile).Contains(metadataSecret)&&shown.Contains("Слишком длинная строка"),"Oversized metadata stream does not leak secrets to logs");}
  var hugeIndex=new StringBuilder();for(int i=0;i<25000;i++)hugeIndex.AppendLine("H normal-file-"+i+"-"+new string('x',40)+".xml");hugeIndex.AppendLine("h hidden-secret.xml");string indexLog=Path.Combine(root,"index-flags.log");using(var memory=new MemoryStream(Encoding.UTF8.GetBytes(hugeIndex.ToString())))using(var reader=new StreamReader(memory,Encoding.UTF8)){var task=(Task)logType.GetMethod("ReadIndexFlagsAsync").Invoke(null,new object[]{reader,indexLog,"stdout",new[]{"hidden-secret"}});task.GetAwaiter().GetResult();var value=task.GetType().GetProperty("Result").GetValue(task,null);Check(((string)value.GetType().GetField("Metadata").GetValue(value)).Contains("h hidden-secret.xml"),"Late hidden flag survives a huge index");Check(((string)value.GetType().GetField("Text").GetValue(value)).Length<200&&!File.ReadAllText(indexLog).Contains("normal-file-")&&!File.ReadAllText(indexLog).Contains("hidden-secret"),"Normal index rows discarded; hidden filenames masked");}
  var editorType=assembly.GetType("OneCConfigExporter.BatchBaseForm");using(var editor=(Form)Activator.CreateInstance(editorType,new object[]{new BatchBase{Name="KA",FileMode=false,Server="localhost",Database="KA",Output=production.Local},new object[0],true,true})){
   editor.Show();Application.DoEvents();editor.PerformLayout();var visible=Descendants(editor).Where(c=>c.Visible&&(c is Button||c is Label)).ToArray();Check(visible.Any(c=>c.Text.Contains("локальные файлы имеют приоритет")),"Policy is visible in base editor");var bounds=editor.RectangleToScreen(editor.ClientRectangle);foreach(var c in visible)Check(bounds.Contains(c.RectangleToScreen(c.ClientRectangle)),"Editor control fits: "+c.Text);using(var image=new Bitmap(editor.Width,editor.Height)){editor.DrawToBitmap(image,new Rectangle(Point.Empty,image.Size));image.Save(Path.Combine(root,"editor.png"));}}
  var fontForm=(Form)Activator.CreateInstance(main,true);Font[] held=new[]{"platformIndicator","gitIndicator","githubIndicator","preview","logBox"}.Select(name=>((Control)main.GetField(name,flags).GetValue(fontForm)).Font).ToArray();fontForm.Dispose();foreach(Font font in held){bool disposed=false;try{font.GetHeight();}catch(ArgumentException){disposed=true;}Check(disposed,"Every owned equal-valued Font instance disposed, not only the first");}
  Console.WriteLine("PASS: local-first push; unrelated/diverged/behind histories; exact tree; both ancestors/backups; bounded retry; dirty/unfinished/auth/protection/size failures; cancellation; tree tampering; private fetch isolation; GUI pipeline and metadata masking; no real GitHub network.");
 }
 static Tuple<int,string> awaitless(string folder,string command){return Native(folder,command).GetAwaiter().GetResult();}
}
