using System;
using System.IO;
using System.Text;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Diagnostics;
using System.Net;
using System.Net.Http;
using System.Windows.Forms;
using OneCConfigExporter;
class VerifyFinalSafety {
 static BindingFlags flags=BindingFlags.Instance|BindingFlags.NonPublic;static Assembly asm;static Type main,paths,store;static string root,git;
 static void Check(bool value,string text){if(!value)throw new Exception(text);}
 static object Call(Type t,string method,params object[] args){try{return t.GetMethod(method,BindingFlags.Static|BindingFlags.Public|BindingFlags.NonPublic).Invoke(null,args);}catch(TargetInvocationException ex){throw ex.InnerException;}}
 static void Wait(Task task){var end=DateTime.UtcNow.AddSeconds(90);while(!task.IsCompleted&&DateTime.UtcNow<end){Application.DoEvents();Thread.Sleep(10);}Check(task.IsCompleted,"Task timeout");task.GetAwaiter().GetResult();}
 static Control C(Form f,string name){return (Control)main.GetField(name,flags).GetValue(f);}
 static Form FormFor(string output){var f=(Form)Activator.CreateInstance(main,true);Action<Control> create=null;create=c=>{var h=c.Handle;foreach(Control child in c.Controls)create(child);};create(f);C(f,"gitPath").Text=git;C(f,"output").Text=output;return f;}
 static Tuple<int,string> Run(Form f,string args,bool auth=false){var task=(Task<Tuple<int,string>>)main.GetMethod("RunGitAsync",flags).Invoke(f,new object[]{args,auth});Wait(task);return task.Result;}
 static void Throws(Action action,string description){bool rejected=false;try{action();}catch{rejected=true;}Check(rejected,description);}
 class FakeHttp : HttpMessageHandler {readonly string text;public FakeHttp(string text){this.text=text;}protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,CancellationToken cancellation){cancellation.ThrowIfCancellationRequested();return Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK){Content=new StringContent(text)});}}
 [STAThread]static void Main(string[] args){
  asm=typeof(UserSettings).Assembly;main=asm.GetType("OneCConfigExporter.MainForm");paths=asm.GetType("OneCConfigExporter.ExecutionSafety");store=asm.GetType("OneCConfigExporter.SettingsStore");git=args[2];root=Path.Combine(args[0],"final-safety-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);
  Check(asm.GetName().Version.ToString()=="2.5.2.0","Assembly version 2.5.2");
  foreach(string bad in new[]{"relative",@"C:relative",Path.GetPathRoot(root),Path.Combine(root,".git","objects"),root+"\n"})Throws(()=>Call(paths,"DirectoryPath",bad),"Unsafe output rejected: "+bad);
  string output=Path.Combine(root,"locked");var lease=asm.GetType("OneCConfigExporter.OutputLease");using(var held=(IDisposable)Call(lease,"Acquire",output)){Throws(()=>Call(lease,"Acquire",output),"Second writer rejected");using(var f=FormFor(output)){C(f,"platform").Text=args[1];var b=new BatchBase{Name="Locked",FileMode=false,Server="test",Database="one",Output=output};main.GetField("batchBases",flags).SetValue(f,new List<BatchBase>{b});main.GetMethod("ReloadBatchRows",flags).Invoke(f,null);Wait((Task)main.GetMethod("RunBatchAsync",flags).Invoke(f,new object[]{false}));Check(!File.Exists(Path.Combine(output,"Configuration.xml")),"Busy output not modified");var grid=(DataGridView)C(f,"batchGrid");Check(Convert.ToString(grid.Rows[0].Cells["Пояснение"].Value).Contains("занят"),"Lock reason visible");}}
  using(var held=(IDisposable)Call(lease,"Acquire",output)){Throws(()=>Call(lease,"Acquire",Path.Combine(output,"nested")),"Child blocked by parent lease");}using(var child=(IDisposable)Call(lease,"Acquire",Path.Combine(output,"nested"))){Throws(()=>Call(lease,"Acquire",output),"Parent blocked by child lease");}using(var released=(IDisposable)Call(lease,"Acquire",output)){}
  string target=Path.Combine(root,"junction-target"),link=Path.Combine(root,"junction-link");Directory.CreateDirectory(target);using(var process=Process.Start(new ProcessStartInfo{FileName=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.System),"cmd.exe"),Arguments="/c mklink /J \""+link+"\" \""+target+"\"",UseShellExecute=false,CreateNoWindow=true,RedirectStandardOutput=true,RedirectStandardError=true})){process.StandardOutput.ReadToEnd();process.StandardError.ReadToEnd();Check(process.WaitForExit(5000)&&process.ExitCode==0,"Test junction created");}Throws(()=>Call(paths,"DirectoryPath",link),"Junction output rejected");Directory.Delete(link,false);
  var filter=asm.GetType("OneCConfigExporter.ExportSizeFilter");object before=Call(filter,"Snapshot",output);foreach(string name in new[]{"Configuration.xml","ConfigDumpInfo.xml", ".onecexporter.lock","run.settings.dat","run.ps1","run.result.json",".gitignore","large.bin"})File.WriteAllBytes(Path.Combine(output,name),new byte[100]);var deleted=(List<string>)Call(filter,"Apply",output,before,30L,args[0]);Check(deleted.Count==1&&!File.Exists(Path.Combine(output,"large.bin"))&&File.Exists(Path.Combine(output,"Configuration.xml")),"Metadata/scripts/lock preserved by filter");using(var cancellation=new CancellationTokenSource()){cancellation.Cancel();Throws(()=>Call(filter,"SnapshotCore",output,cancellation.Token),"Snapshot cancellation");}
  var invalid=new UserSettings{GithubToken="x\r\ny"};Throws(()=>Call(store,"Save",Path.Combine(root,"invalid.dat"),invalid),"Multiline token rejected");invalid=new UserSettings{GithubToken=new string('x',5000)};Throws(()=>Call(store,"Save",Path.Combine(root,"invalid.dat"),invalid),"Oversized field rejected");
  string config=Path.Combine(root,"valid.settings.dat");var settings=new UserSettings{Platform=args[1],BatchBases=new List<BatchBase>{new BatchBase{Name="CLI",FileMode=false,Server="test",Database="one",Output=Path.Combine(root,"automatic")}}};Call(store,"Save",config,settings);string signature=(string)Call(store,"Signature",config);Call(store,"Save",config,settings);Throws(()=>Call(store,"SaveChecked",config,settings,signature,false),"Stale writer does not overwrite settings");byte[] original=File.ReadAllBytes(config);using(var f=FormFor(output)){string report=Path.Combine(root,"run.result.json");var task=(Task<int>)main.GetMethod("RunAutomatic").Invoke(f,new object[]{config,report});Wait(task);Check(task.Result==0&&File.ReadAllText(report).Contains("Completed"),"Atomic final report");Check(Convert.ToBase64String(original)==Convert.ToBase64String(File.ReadAllBytes(config)),"Automatic snapshot not rewritten");}
  using(var f=FormFor(output)){var task=(Task<int>)main.GetMethod("RunAutomatic").Invoke(f,new object[]{config,config});Wait(task);Check(task.Result==2&&Convert.ToBase64String(original)==Convert.ToBase64String(File.ReadAllBytes(config)),"Report cannot overwrite settings");}
  string script=Path.Combine(root,"scenario's name.ps1");Call(asm.GetType("OneCConfigExporter.AutomaticScenario"),"Write",script,asm.Location,settings);byte[] scriptBytes=File.ReadAllBytes(script);Check(scriptBytes[0]==239&&scriptBytes[1]==187&&scriptBytes[2]==191,"PowerShell UTF8 BOM");string scriptConfig=Path.Combine(root,"scenario's name.settings.dat");using(var held=new FileStream(scriptConfig+".lock",FileMode.Open,FileAccess.ReadWrite,FileShare.None))Throws(()=>Call(asm.GetType("OneCConfigExporter.AutomaticScenario"),"Write",script,asm.Location,settings),"Running snapshot cannot be replaced");Throws(()=>Call(asm.GetType("OneCConfigExporter.AutomaticScenario"),"Write",Path.Combine(root,"bad.exe"),asm.Location,settings),"Scenario extension checked");
  string repo=Path.Combine(root,"repo");Directory.CreateDirectory(repo);using(var f=FormFor(repo)){foreach(string command in new[]{"init --initial-branch=main","config user.name Test","config user.email test@example.invalid"})Check(Run(f,command).Item1==0,"Git fixture");File.WriteAllText(Path.Combine(repo,"stage.txt"),"pending");Check(Run(f,"add stage.txt").Item1==0,"Stage fixture");var preflight=(Task<string>)main.GetMethod("GitPreflight",flags).Invoke(f,null);Wait(preflight);Check(preflight.Result.Contains("подготовленные"),"Existing staged changes protected");Check(Run(f,"rm --cached stage.txt").Item1==0,"Unstage fixture");File.WriteAllText(Path.Combine(repo,".git","MERGE_HEAD"),"test");preflight=(Task<string>)main.GetMethod("GitPreflight",flags).Invoke(f,null);Wait(preflight);Check(preflight.Result.Contains("MERGE_HEAD"),"Merge protected");File.Delete(Path.Combine(repo,".git","MERGE_HEAD"));
   string previous=Environment.GetEnvironmentVariable("GIT_DIR");Environment.SetEnvironmentVariable("GIT_DIR",Path.Combine(root,"does-not-exist"));try{Check(Run(f,"rev-parse --is-inside-work-tree").Item2=="true","Injected GIT_DIR ignored");}finally{Environment.SetEnvironmentVariable("GIT_DIR",previous);}
   Check(Run(f,"config url.https://invalid.example/.insteadOf https://github.com/").Item1==0,"Rewrite fixture");var blocked=Run(f,"status --porcelain",true);Check(blocked.Item1!=0&&blocked.Item2.Contains("insteadOf"),"Token use blocked with URL rewrite, no network command executed");
  }
  using(var client=new HttpClient(new FakeHttp(new string('x',2*1024*1024+1)))){var task=(Task<string>)main.GetMethod("GithubResponse",BindingFlags.Static|BindingFlags.NonPublic).Invoke(null,new object[]{client,"https://example.invalid/",CancellationToken.None});Throws(()=>Wait(task),"HTTP response bounded without network");}
  Console.WriteLine("PASS: v2.5.2; unsafe paths; output lock; metadata filter protection; cancellation; settings bounds; immutable scenario snapshot; atomic report; collision protection; BOM; locked scenario; staged/merge protection; GIT_DIR isolation; URL rewrite protection; bounded mock HTTP.");Console.WriteLine("SCRIPT="+script);
 }
}
